### PR TITLE
Implemented bcl2fastq2 module Fixes #11 

### LINKED ISSUE #11: Implement bcl2fastq2 module
Amend app to include data from bcl2fastq2 QC in multiqc summary. 
Remove -m flags from code.sh calling multiqc specifying which modules to run as multiqc autodetects the input and calls the correct modules.
Check whether the bcl2fastq2 output file Stats.json exists before attempting to download as 'dx download' will cause app to crash if file not present.

### PR DESCRIPTION
**Pull request by Graeme-Smith**
The code changes have been tested on dnanexus - both with a project containing a Stats.json file and one without. When the json file was present the data it held was included in the MultiQC summary, when the Stats.json file was absent it was noted in the output log and the app successfully proceeded to produce a MultiQC summary without including this information.

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/13)

### CODE REVIEW

**Comment by aledj2** [comment]
Reviewed 1 of 1 files at r1, 1 of 2 files at r4.
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 1 at r4](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-Kz3WKF669NYUfQEZjb5:-Kz3WKF669NYUfQEZjb6:b-xg2laz) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/6387a69678aa06bf7965bb7d1a82e32363b3298d/README.md#L1)):*
> ```Markdown
> # dnanexus_multiqc 
> ```

Can we keep the DNA Nexus release on the top line and maybe state that it uses multiqc release 1.3 (I know it's confusing that it's the same version number but I think it's important to clearly state the nexus app version release in the top line in line with all other apps)

---

*[README.md, line 24 at r4](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-Kz3WRnIAmSGoDvyDvEA:-Kz3WRnIAmSGoDvyDvEB:bjwvmuk) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/6387a69678aa06bf7965bb7d1a82e32363b3298d/README.md#L24)):*
> ```Markdown
> * base_distribution_by_cycle_metrics
> * output.metrics
> Additionally the project folder must have a Stats.json file in Data/Intensities/BaseCalls/Stats in order to
> ```

stats.json file from Data/Intensities/BaseCalls/Stats (if demultiplexing was performed by bcl2fastq v2.20 (or later)) 

---

*[src/code.sh, line 28 at r4](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-Kz3Xl7oixxKeg9bdVvZ:-Kz3Xl7oixxKeg9bdVv_:bbr5d5w) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/6387a69678aa06bf7965bb7d1a82e32363b3298d/src/code.sh#L28)):*
> ```Shell
> # Stats.json is the exception. It is uploaded with the runfolder at Data/Intesities/BaseCalls/Stats/.
> # This search makes sure it is found in the project/runfolder regardless of project name.
> stats_json=$(dx find data --path ${project_for_multiqc}: --name "Stats.json" | cut -f8 -d ' ' | tr -d '()')
> ```

can you explain what cut and tr does here please, maybe give an example path etc to show what exactly you're extracting

---

*[src/code.sh, line 30 at r4](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-Kz3XvebjT_IhahP0535:-Kz3XvebjT_IhahP0536:b71iver) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/6387a69678aa06bf7965bb7d1a82e32363b3298d/src/code.sh#L30)):*
> ```Shell
> stats_json=$(dx find data --path ${project_for_multiqc}: --name "Stats.json" | cut -f8 -d ' ' | tr -d '()')
> # If stats.json file is present download
> if [[ $stats_json =~ ^"file" ]]
> ```

what does =~ ^ do?

---

*[src/code.sh, line 59 at r4](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-Kz3Y3hEvcrPWlH279Hm:-Kz3Y3hFMWoCiM3ac2n5:b-uuu9l2) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/6387a69678aa06bf7965bb7d1a82e32363b3298d/src/code.sh#L59)):*
> ```Shell
> 
> # Test MultiQC from development branch of moka-guys fork
> # git clone -b dev_v1.3 https://github.com/moka-guys/MultiQC.git
> ```

can we remove these comments please

---

*[src/code.sh, line 77 at r4](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-Kz3Y7jFJCQFUr9ktvVj:-Kz3Y7jFJCQFUr9ktvVk:bl2f05v) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/6387a69678aa06bf7965bb7d1a82e32363b3298d/src/code.sh#L77)):*
> ```Shell
> 
> # Run multiQC
> # # command is : multiqc <dir containing files> -m module1 -m module2 -n <path/to/output>
> ```

can we update this comment please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13)*

**Comment by NMNS93** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/code.sh, line 30 at r4](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-Kz3XvebjT_IhahP0535:-Kz4Hu8cs22XaFqxBsQe:b-g7h41) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/6387a69678aa06bf7965bb7d1a82e32363b3298d/src/code.sh#L30)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what does =~ ^ do?
</blockquote></details>

Realise now I could have responded to this here but did so in comment, see revision 5!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13)*

**Comment by aledj2** [comment]
Reviewed 1 of 1 files at r6.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/code.sh, line 32 at r6](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-L-a2qGXUB3FCNAexEm0:-L-a2qGY7dIiR1xygmob:brdtta0) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/501a17e26ef31768bbc27abff107f98812557101/src/code.sh#L32)):*
>  cut -f8 -d ' '
using a space as a delimiter the file-id is the 8th element in the list

---

*[src/code.sh, line 32 at r6](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-L-a35Rcx0aWy65c0K_E:-L-a35RdbsE5jE1PE7hC:b-1y0vcs) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/501a17e26ef31768bbc27abff107f98812557101/src/code.sh#L32)):*
>  tr -d '()'
delete all characters in this list (brackets)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13)*

**Comment by aledj2** [comment]
I've taken so long with this could we get it ready for peddy also? ie add the required dx download command please? guess it'd have to be similar to stats.json - this could wait for a later release if you'd prefer

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-:-L055cKYiQDx-VllIdsS:blfkkj)*

**Comment by aledj2** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/code.sh, line 23 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-L057BEMUm_p0_8OQpdM:-L057BEN5z2bOSOe89Iy:bgpgmyi) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/013957bec6d8b897dc9c2fe034462a37aa979edb/src/code.sh#L23)):*
> ```Shell
> dx download $project_for_multiqc:QC/*insert_size_metrics --auth $API_KEY
> dx download $project_for_multiqc:QC/*output.metrics --auth $API_KEY
> dx download $project_for_multiqc:QC/*stats-fastqc.txt --auth $API_KEY
> ```

add in a dx download for the peddy output?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13)*

**Comment by NMNS93** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/code.sh, line 23 at r7](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13#-L057BEMUm_p0_8OQpdM:-L09RKbPsDVe8DaFETws:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/013957bec6d8b897dc9c2fe034462a37aa979edb/src/code.sh#L23)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

add in a dx download for the peddy output?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13)*

**Comment by aledj2** [comment]
Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/13)*

**Pull request merged**
