### PR TITLE
Integration of SEGLH MultiQC plugin v1.15.0

### PR DESCRIPTION
**Pull request by preciserobot**
Added SEGLH plugin for multiQC
renamed docker image to reflect integrated SEGLH plugin  (seglh/multiqc:v1.11)

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43)

### CODE REVIEW

**Review by Graeme-Smith — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @aledj2 and @preciserobot)

___
*[src/code.sh, line 105 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43#-Msp8Y9K2Rh64RHLaozS:-Msp8Y9K2Rh64RHLaozT:b-x8i515) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/84c51e65e4585cd6eea5b5ce69cb43b8c3f29512/src/code.sh#L105)):*
> ```Shell
>     # remove the template file so it doesn't appear on final report
>     rm sention_output_metrics_header
> ```

Why is this code now commented out?

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43)* status: all files reviewed, 2 unresolved discussions (waiting on @aledj2 and @preciserobot)

___
*[README.md, line 55 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43#-MtCjb503F0tfJ7ZGE-0:-MtCjb503F0tfJ7ZGE-1:bbrvaw7) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/578e635e3e2981f56e9a1b7a11b0d82a793b80c5/README.md#L55)):*
> ```Markdown
> 1. The app downloads all files (recursively) within the QC/ directory of the project. 
> 2. The dx_find_and_download function is used to search for specific files, which are downloaded only if found.
> 3. If sention duplication_metrics files are present the app replaces the header (with a template packaged in the app) 
> ```

Is this step still relevant?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ErinPeat, @Graeme-Smith, @natashapinto, and @preciserobot)

___
*[src/code.sh, line 105 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43#-Msp8Y9K2Rh64RHLaozS:-MtA1HQhEKqDKFPbXMkX:bo4037l) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/84c51e65e4585cd6eea5b5ce69cb43b8c3f29512/src/code.sh#L105)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

Why is this code now commented out?
</blockquote></details>

removed - legacy code that is no longer required (multiqc now supports senteion)

**Review by ErinPeat — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43)* status: all files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith and @preciserobot)

**Review by ErinPeat — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43)* status: all files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith and @preciserobot)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43)* status: all files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith and @natashapinto)

___
*[README.md, line 55 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43#-MtCjb503F0tfJ7ZGE-0:-MtDBPyW3B3_GOvk88Y5:bb7f2mf) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/578e635e3e2981f56e9a1b7a11b0d82a793b80c5/README.md#L55)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

Is this step still relevant?
</blockquote></details>

done

**Review by ErinPeat — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/43)* status: all files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith and @natashapinto)

**Pull request merged**
