### PR TITLE
Change app so it works with Dragen pipeline and peddy/verifyBAMID

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_multiqc/18)

### CODE REVIEW

**Comment by andyb3** [comment]
+@andyb3 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18#-:-L2eh6d0ARz0O3AS2tmY:bxccsfn)*

**Comment by andyb3** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/code.sh, line 22 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18#-L2eltJ_exowTZc8ZSu2:-L2eltJ_exowTZc8ZSu3:b7oy1eq) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/97c52e1a545921e9672850ec272afa7c1bdcf4c7/src/code.sh#L22)):*
> ```Shell
> dx download $project_for_multiqc:QC/* --auth $API_KEY
> 
> # check if there are any dragen output files
> ```

Maybe make it clear in the comment that the dragen output files are named mapping_metrics.csv

---

*[src/code.sh, line 26 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18#-L2elP1hAq0lg6k0Yneu:-L2elP1i4iKWKLUf_yEf:b-juyz1p) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/97c52e1a545921e9672850ec272afa7c1bdcf4c7/src/code.sh#L26)):*
> ```Shell
> # list all files in the output folder
> # pass this list to grep using -c which just outputs the count of files which match mapping_metrics
> mapping_metrics_count=$(dx find data --path ${project_for_multiqc}: --name "*mapping_metrics.csv" --auth $API_KEY | wc -l)
> ```

comment says you're using grep but actually using dx find data?

---

*[src/code.sh, line 72 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18#-L2emNj_Dvw6mNTd3nzP:-L2emNj_Dvw6mNTd3nzQ:b8urnii) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/97c52e1a545921e9672850ec272afa7c1bdcf4c7/src/code.sh#L72)):*
> ```Shell
> #export to path
> export PATH="$HOME/Miniconda/bin:$PATH"
> #conda update -y
> ```

Is this meant to be commented out? Can it be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18)*

**Comment by aledj2** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/code.sh, line 22 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18#-L2eltJ_exowTZc8ZSu2:-L2eyTYhO1nPC9IPJrCx:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/97c52e1a545921e9672850ec272afa7c1bdcf4c7/src/code.sh#L22)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Maybe make it clear in the comment that the dragen output files are named mapping_metrics.csv
</blockquote></details>

Done.

---

*[src/code.sh, line 26 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18#-L2elP1hAq0lg6k0Yneu:-L2eyXuwn4JsF9Jqmsw9:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/97c52e1a545921e9672850ec272afa7c1bdcf4c7/src/code.sh#L26)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

comment says you're using grep but actually using dx find data?
</blockquote></details>

Done.

---

*[src/code.sh, line 72 at r1](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18#-L2emNj_Dvw6mNTd3nzP:-L2eyYFjZQh8V7AioJEP:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_multiqc/blob/97c52e1a545921e9672850ec272afa7c1bdcf4c7/src/code.sh#L72)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Is this meant to be commented out? Can it be removed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18)*

**Comment by andyb3** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/dnanexus_multiqc/18#-:-L2ezYSb0hOFbs7Xy6AI:bnfp4nl)*

**Pull request merged**
